package com.Hr_Management.Enum;

public enum Permissions {
 CREATE_EMPLOYEE,UPDATE_EMPLOYEE,DELETE_EMPLOYEE,VIEW_EMPLOYEE, 
 APPLY_LEAVE,APPOVE_LEAVE,VIEW_ATTENDENCE,APPLY_WFH,VIEW_HOLIDAYS,APPOVE_WFH,
 RUN_PAYROLE,VIEW_PAYROLE,VIEW_ANALYTICES
}
