spring.application.name=Hr_Management

spring.datasource.url=jdbc:mysql://localhost:3306/hr_managemant
spring.datasource.username=root
spring.datasource.password=123456
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MySQL Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=8080